bar/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
	# usual views of object listings
	url(r'^$',                       views.index,                          name='main_menu'),
	url(r'^food_material_list$',     views.FoodMaterialListView.as_view(), name='food_material_list'),
	url(r'^product_list$',           views.ProductListView.as_view(),      name='product_list'),
	url(r'^sale_offer_list$',        views.SaleOfferListView.as_view(),    name='sale_offer_list'),
	url(r'^transaction_list$',       views.TransactionListView.as_view(),  name='transaction_list'),
	
	# import services
	url(r'^food_material_import$',   views.food_material_import,           name='food_material_import'),
	url(r'^simple_product_import$',  views.simple_product_import,          name='simple_product_import'),
	url(r'^complex_product_import$', views.complex_product_import,         name='complex_product_import'),
	
	# forms and buttons
	url(r'^sale_offer_generator$',   views.sale_offer_generator,           name='sale_offer_generator'),
	url(r'^add_transaction$',        views.add_transaction_form,           name='add_transaction'),
	url(r'^add_account$',            views.add_account_form,               name='add_account'),
]

tango3/urls.py
from django.conf.urls import include, url
from django.contrib   import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bar/',   include('bar.urls', namespace='bar')),
]

bar/models.py
from django.db                  import models
from django.db.models           import Sum
from django.db.models.functions import Coalesce

import decimal
import math


class WorkDay(models.Model):
	date       = models.DateField()
	is_current = models.BooleanField(default=False)
	
	class Meta:
		ordering = ['-date']
	
	def __str__(self):
		return str(self.date)
	
	def save(self, *args, **kwargs):
		if self.is_current:
			WorkDay.objects.filter(is_current=True).update(is_current=False)
		return super(WorkDay, self).save(*args, **kwargs)
	
	@staticmethod
	def get_current():
		return WorkDay.objects.get(is_current=True)


class FoodMaterial(models.Model):
	name      = models.CharField(max_length=200)
	unit_name = models.CharField(max_length=200, blank=True, default='')
	
	class Meta:
		ordering = ['name']
	
	def __unicode__(self):
		return self.name
	
	def __str__(self):
		return self.name
	
	def get_item(self, date):
		"""
		Getting last item of food material in the bar store just for calculating unit cost.
		"""
		item = FoodMaterialItem.objects.filter(food_material=self, when__date__lte=date)
		if not item.exists():
			return None
		
		return item.order_by('-when__date')[0]
	
	def get_item_with_rest(self):
		"""
		Getting not empty food material in the bar store (not empty bottle of something).
		"""
		item = FoodMaterialItem.objects.filter(food_material=self, rest__gt=0)
		if not item.exists():
			return None
		
		return item.order_by('when__date')[0]
	
	def get_cost(self, date):
		"""
		Getting the unit cost of the food material by the date.
		"""
		item = self.get_item(date)
		if not item:
			return decimal.Decimal(0)
		
		return item.unit_cost
	
	def get_rest(self, day=None):
		"""
		Getting the rest of the food material in the bar store by now.
		"""
		if day is None: day = WorkDay.get_current()
		return FoodMaterialCachedRest.get_count(self, day)
	
	def get_spend(self):
		"""
		Getting the spend of the food material in all time.
		"""
		result = FoodMaterialSpend.objects.filter(food_material=self, count__gt=0).aggregate(Sum('count'))
		if result['count_sum'] is None:
			return decimal.Decimal(0)
		return result['count_sum']
	
	def make_spend(self, count, transaction):
		rest = count
		for item in FoodMaterialItem.objects.filter(food_material=self, rest__gt=0).order_by('when__date'):
			if rest <= decimal.Decimal(0):
				break
			
			if item.rest >= rest:
				item.rest -= rest
				item.save()
				rest = decimal.Decimal(0)
				continue
			
			if item.rest < rest:
				rest -= item.rest
				item.rest = decimal.Decimal(0)
				item.save()
				continue
		
		FoodMaterialSpend.create(self, transaction, count - rest)


class FoodMaterialItem(models.Model):
	food_material = models.ForeignKey(FoodMaterial)
	when          = models.ForeignKey(WorkDay)
	cost          = models.DecimalField(max_digits=8, decimal_places=2)
	count         = models.DecimalField(max_digits=8, decimal_places=4)
	rest          = models.DecimalField(max_digits=8, decimal_places=4, default=0)
	unit_cost     = models.DecimalField(max_digits=8, decimal_places=2, default=0)
	
	class Meta():
		ordering = ['-when__date']
	
	def __unicode__(self):
		return unicode(self.food_material) + ' (' + str(self.when) + ')'
	
	def __str__(self):
		return unicode(self.food_material) + ' (' + str(self.when) + ')'
	
	def save(self, *args, **kwargs):
		self.unit_cost = decimal.Decimal(self.cost) / decimal.Decimal(self.count)
		self.unit_cost = self.unit_cost.quantize(self.cost, rounding=decimal.ROUND_UP)
		
		if not self.pk and self.rest is None:
			self.rest = self.count
		
		return super(FoodMaterialItem, self).save(*args, **kwargs)
	
	@staticmethod
	def get_rest(material, day):
		if not FoodMaterialItem.objects.filter(
				food_material   = material, 
				rest__gt        = 0, 
				when__date__lte = day.date
			).exists():
			return decimal.Decimal(0)
		items = FoodMaterialItem.objects.filter(
				food_material   = material, 
				rest__gt        = 0, 
				when__date__lte = day.date
			).aggregate(Sum('rest'))
		return items['rest__sum']


class FoodMaterialCachedRest(models.Model):
	food_material = models.ForeignKey(FoodMaterial)
	when          = models.ForeignKey(WorkDay)
	count         = models.DecimalField(max_digits=8, decimal_places=4)
	
	class Meta():
		ordering = ['-when__date']
	
	@staticmethod
	def create(material, day):
		items  = FoodMaterialItem.get_rest(material, day)
		spends = FoodMaterialSpend.get_count(material, day)
		count  = items - spends
		rest   = FoodMaterialCachedRest(
				food_material = material,
				when          = day,
				count         = count
			)
		rest.save()
		return rest
	
	@staticmethod
	def get_count(material, day):
		if FoodMaterialCachedRest.objects.filter(food_material=material, when=day).exists():
			return FoodMaterialCachedRest.objects.get(food_material=material, when=day).count
		rest = FoodMaterialCachedRest.create(material, day)
		return rest.count
	
	@staticmethod
	def clear_from(material, day):
		FoodMaterialCachedRest.objects.filter(
				food_material   = material, 
				when__date__gte = day.date
			).delete()


class Recipe(models.Model):
	name    = models.CharField(max_length=200)
	comment = models.TextField(blank=True)
	process = models.TextField(blank=True)
	
	class Meta:
		ordering = ['name']
	
	def __unicode__(self):
		return self.name
	
	def __str__(self):
		return self.name


class RecipeIngredient(models.Model):
	recipe        = models.ForeignKey(Recipe)
	food_material = models.ForeignKey(FoodMaterial)
	extra_action  = models.CharField(max_length=250, blank=True)
	count         = models.DecimalField(max_digits=8, decimal_places=4)
	
	def __unicode__(self):
		return unicode(self.food_material) + ' x ' + str(self.count)
	
	def __str__(self):
		return unicode(self.food_material) + ' x ' + str(self.count)


class Calculation(models.Model):
	when_date       = models.DateField()
	what_name       = models.CharField(max_length=200)
	what_unit_cost  = models.DecimalField(max_digits=8, decimal_places=2)
	what_count      = models.DecimalField(max_digits=8, decimal_places=4)
	what_unit_name  = models.CharField(max_length=200)
	what_full_cost  = models.DecimalField(max_digits=8, decimal_places=2)
	feasible        = models.BooleanField(default=False)
	on_prescription = models.ForeignKey(Recipe)
	on_ingredient   = models.ForeignKey(RecipeIngredient, default=None)
	
	@staticmethod
	def create(ingredient):
		work_day = WorkDay.get_current()
		Calculation.objects.filter(
				when_date     = work_day.date, 
				on_ingredient = ingredient).delete()
		
		calculation = Calculation()
		calculation.when_date       = work_day.date
		calculation.what_name       = ingredient.food_material.name
		calculation.what_unit_cost  = ingredient.food_material.get_cost(work_day.date)
		calculation.what_count      = ingredient.count
		calculation.what_unit_name  = ingredient.food_material.unit_name
		calculation.on_prescription = ingredient.recipe
		calculation.on_ingredient   = ingredient
		calculation.feasible        = ingredient.food_material.get_rest() >= ingredient.count
		calculation.save()
		
		return calculation
	
	def save(self, *args, **kwargs):
		self.what_full_cost = self.what_unit_cost * self.what_count
		self.what_full_cost = self.what_full_cost.quantize(decimal.Decimal('.01'), rounding=decimal.ROUND_UP)
		
		return super(Calculation, self).save(*args, **kwargs)


class Product(models.Model):
	name        = models.CharField(max_length=200)
	recipe      = models.OneToOneField(Recipe)
	fixed_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
	rounding    = models.DecimalField(max_digits=8, decimal_places=2, default=1)
	markup      = models.DecimalField(max_digits=8, decimal_places=2, default=1)
	is_active   = models.BooleanField(default=True)
	
	def __unicode__(self):
		return self.name
	
	def __str__(self):
		return self.name
	
	def make_price(self, cost):
		price = (cost * self.markup) / (decimal.Decimal(10)**self.rounding)
		price = price.quantize(decimal.Decimal('1'), rounding=decimal.ROUND_UP)
		price = price * (decimal.Decimal(10)**self.rounding)
		
		if self.fixed_price > price:
			price = self.fixed_price
		if price > self.fixed_price:
			print('calculated price is more than fixed')
		
		return price


class SaleOffer(models.Model):
	product  = models.ForeignKey(Product)
	day      = models.ForeignKey(WorkDay)
	cost     = models.DecimalField(max_digits=8, decimal_places=2, default=decimal.Decimal('0.00'))
	price    = models.DecimalField(max_digits=8, decimal_places=2, default=decimal.Decimal('0.00'))
	feasible = models.BooleanField(default=False)
	
	class Meta:
		ordering = ('product__name',)
	
	def __unicode__(self):
		return unicode(self.product) + ' (' + str(self.day) + ') -- ' + str(self.price)
	
	def __str__(self):
		return unicode(self.product) + ' (' + str(self.day) + ') -- ' + str(self.price)
	
	def save(self, *args, **kwargs):
		cost     = decimal.Decimal('0.00')
		price    = decimal.Decimal('0.00')
		feasible = True
		
		ingredients = RecipeIngredient.objects.filter(recipe=self.product.recipe)
		for ingredient in ingredients:
			calculation = Calculation.create(ingredient)
			cost += calculation.what_full_cost
			
			if not calculation.feasible:
				feasible = False
		
		self.cost     = cost
		self.price    = self.product.make_price(cost)
		self.feasible = feasible
		
		return super(SaleOffer, self).save(*args, **kwargs)
	
	@staticmethod
	def generate():
		day = WorkDay.get_current()
		existed = SaleOffer.objects.filter(day=day).values_list('product', flat=True)
		
		for product in Product.objects.filter(is_active=True):
			if product.id in existed:
				continue
			
			offer = SaleOffer(
				product = product,
				day     = day
			)
			offer.save()


class Account(models.Model):
	name       = models.CharField(max_length=200)
	is_default = models.BooleanField(default=False)
	costed     = models.BooleanField(default=False)
	
	def __unicode__(self):
		return self.name

bar/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators        import login_required
from django.http                           import HttpResponse
from django.shortcuts                      import render, redirect, get_object_or_404
from django.utils.decorators               import method_decorator
from django.views                          import generic

from .models   import FoodMaterial, Product, SaleOffer, WorkDay, Account, AccountTransaction
from .services import FoodMaterialImportService, SimpleProductImportService, ComplexProductImportService


def index(request):
	return render(request, 'bar/main_menu.html', {})


@staff_member_required
def food_material_import(request):
	if request.FILES and request.FILES['import']:
		FoodMaterialImportService.run(request.FILES['import'])
	return redirect('bar:food_material_list')


@staff_member_required
def simple_product_import(request):
	if request.FILES and request.FILES['import']:
		SimpleProductImportService.run(request.FILES['import'], request.POST['prefix'])
	return redirect('bar:product_list')


@staff_member_required
def complex_product_import(request):
	if request.FILES and request.FILES['import']:
		ComplexProductImportService.run(request.FILES['import'], request.POST['prefix'])
	return redirect('bar:product_list')


@staff_member_required
def sale_offer_generator(request):
	SaleOffer.generate()
	return redirect('bar:sale_offer_list')


@staff_member_required
def add_transaction_form(request):
	if request.POST['sale_offer'] and request.POST['account']:
		transaction = AccountTransaction(
			account    = get_object_or_404(Account,   pk=request.POST['account']),
			sale_offer = get_object_or_404(SaleOffer, pk=request.POST['sale_offer']),
			day        = WorkDay.get_current()
		)
		transaction.save()
	return redirect('bar:transaction_list')


@staff_member_required
def add_account_form(request):
	if request.POST['name']:
		account = Account(
			name       = request.POST['name'],
			is_default = request.POST.get('is_default', False),
			costed     = request.POST.get('costed',     False),
		)
		account.save()
	return redirect('bar:transaction_list')


class FoodMaterialListView(generic.ListView):
	model               = FoodMaterial
	template_name       = 'bar/food_material_list.html'
	context_object_name = 'food_materials'
	
	def get_context_data(self, **kwargs):
		context = super(FoodMaterialListView, self).get_context_data(**kwargs)
		context['user']  = self.request.user
		return context


class ProductListView(generic.ListView):
	model               = Product
	template_name       = 'bar/product_list.html'
	context_object_name = 'products'
	
	def get_queryset(self):
		return Product.objects.order_by('name')
	
	def get_context_data(self, **kwargs):
		context = super(ProductListView, self).get_context_data(**kwargs)
		context['user']  = self.request.user
		return context


class SaleOfferListView(generic.ListView):
	model               = SaleOffer
	template_name       = 'bar/sale_offer_list.html'
	context_object_name = 'sale_offers'
	
	def get_queryset(self):
		day = WorkDay.get_current()
		if self.request.user.is_authenticated():
			return SaleOffer.objects.filter(day=day)
		else:
			return SaleOffer.objects.filter(day=day, feasible=True)
	
	def get_context_data(self, **kwargs):
		context = super(SaleOfferListView, self).get_context_data(**kwargs)
		context['user']  = self.request.user
		context['today'] = WorkDay.get_current()
		return context


class TransactionListView(generic.ListView):
	model               = AccountTransaction
	template_name       = 'bar/transaction_list.html'
	context_object_name = 'transactions'
	
	@method_decorator(login_required(login_url='/admin/login/'))
	def dispatch(self, request, *args, **kwargs):
		return super(TransactionListView, self).dispatch(request, *args, **kwargs)
	
	def get_queryset(self):
		day = WorkDay.get_current()
		return AccountTransaction.objects.filter(day=day)
	
	def get_context_data(self, **kwargs):
		day = WorkDay.get_current()
		
		context = super(TransactionListView, self).get_context_data(**kwargs)
		context['user']     = self.request.user
		context['today']    = day
		context['offers']   = SaleOffer.objects.filter(day=day, feasible=True)
		context['accounts'] = Account.objects.all()
		context['totals']   = AccountTransaction.get_totals(day)
		return context

bar/templates/bar/food_material_list.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	{% load staticfiles %}
	<link href={% static "favicon.ico" %} rel="shortcut icon">
	<link rel="stylesheet" href={% static "css/style.css" %}>
	<title></title>  
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>
	<div class="container">

		<header class="header clearfix">
			<div class="logo">
				tango3.bar<br/>
				{{ user }}
			</div>

			<nav class="menu_main">
				<ul>
					<li class="active"><a href={% url 'bar:food_material_list' %}>food materials</a></li>
					<li><a href={% url 'bar:product_list' %}>products</a></li>
					<li><a href={% url 'bar:sale_offer_list' %}>sale offers</a></li>
					<li><a href={% url 'bar:transaction_list' %}>transactions</a></li>
				</ul>
			</nav>
		</header>
		
		<div class="info">
			<article class="article clearfix">
				<div class="col_33">
					{% if user.is_authenticated %}
						<form action={% url 'bar:food_material_import' %} method="post" enctype="multipart/form-data">
							<h2>tsv import</h2>
							{% csrf_token %}
							<input type="file" name="import" />
							<input type="submit" class="button" />
						</form>
					{% else %}
						&nbsp;
					{% endif %}
				</div>
				
				<div class="col_66">
					{% if food_materials %}
					<h2>food materials</h2>
					
					<table class="table">
						<tr>
							<th>name</th>
							<th>unit</th>
						</tr>
						{% for material in food_materials %}
							<tr>
								<td>{{ material }}</td>
								<td>{{ material.unit_name }}</td>
							</tr>
						{% endfor %}
					</table>
					{% else %}
						<p>no records</p>
					{% endif %}
				</div>
			</article>
		</div>
	</div>
</body>

bar/templates/bar/main_menu.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href={% static "favicon.ico" %} rel="shortcut icon">
  <link rel="stylesheet" href={% static "css/style.css" %}>
  <title></title>  
  <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>
	<div class="container">

		<header class="header clearfix">
			<div class="logo">
				tango3.bar<br/>
				{{ user }}
			</div>

			<nav class="menu_main">
				<ul>
					<li><a href={% url 'bar:food_material_list' %}>food materials</a></li>
					<li><a href={% url 'bar:product_list' %}>products</a></li>
					<li><a href={% url 'bar:sale_offer_list' %}>sale offers</a></li>
					<li><a href={% url 'bar:transaction_list' %}>transactions</a></li>
				</ul>
			</nav>
		</header>
	</div>
</body>

bar/templates/bar/product_list.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	{% load staticfiles %}
	<link href={% static "favicon.ico" %} rel="shortcut icon">
	<link rel="stylesheet" href={% static "css/style.css" %}>
	<title></title>  
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>
	<div class="container">

		<header class="header clearfix">
			<div class="logo">
				tango3.bar<br/>
				{{ user }}
			</div>

			<nav class="menu_main">
				<ul>
					<li><a href={% url 'bar:food_material_list' %}>food materials</a></li>
					<li class="active"><a href={% url 'bar:product_list' %}>products</a></li>
					<li><a href={% url 'bar:sale_offer_list' %}>sale offers</a></li>
					<li><a href={% url 'bar:transaction_list' %}>transactions</a></li>
				</ul>
			</nav>
		</header>

		<div class="info">
			<article class="article clearfix">
				<div class="col_33">
					{% if user.is_authenticated %}
						<form action={% url 'bar:simple_product_import' %} method="post" enctype="multipart/form-data">
							<h2>simple product import</h2>
							{% csrf_token %}
							<input type="text" name="prefix" value="порция" />
							<input type="file" name="import" />
							<input type="submit" class='button'/>
						</form>

						<form action={% url 'bar:complex_product_import' %} method="post" enctype="multipart/form-data">
							<h2>complex product import</h2>
							{% csrf_token %}
							<input type="text" name="prefix" value="коктейль" />
							<input type="file" name="import" />
							<input type="submit" class='button'/>
						</form>
					{% else %}
						&nbsp;
					{% endif %}
				</div>
				
				<div class="col_66">
					{% if products %}
						<h2>product list</h2>
						<table class="table">
							<tr>
								<th>name</th>
								<th>active</th>
							</tr>
							{% for product in products %}
								<tr>
									<td>{{ product.name }}</td>
									<td>{% if product.is_active %}V{% endif %}</td>
								</tr>
							{% endfor %}
						</table>
					{% else %}
						no records
					{% endif %}
				</div>
			</article>
		</div>
	</div>
</body>

bar/templates/bar/sale_offer_list.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	{% load staticfiles %}
	<link href={% static "favicon.ico" %} rel="shortcut icon">
	<link rel="stylesheet" href={% static "css/style.css" %}>
	<title></title>  
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>
	<div class="container">

		<header class="header clearfix">
			<div class="logo">
				tango3.bar<br/>
				{{ user }}
			</div>
			
			<nav class="menu_main">
				<ul>
					<li><a href={% url 'bar:food_material_list' %}>food materials</a></li>
					<li><a href={% url 'bar:product_list' %}>products</a></li>
					<li class="active"><a href={% url 'bar:sale_offer_list' %}>sale offers</a></li>
					<li><a href={% url 'bar:transaction_list' %}>transactions</a></li>
				</ul>
			</nav>
		</header>
		
		<div class="info">
			<article class="article clearfix">
				
				<div class="col_33">
					{% if user.is_authenticated %}
						<!-- TODO: it must be chenged into POST form -->
						<a href={% url 'bar:sale_offer_generator' %}>generating</a>
					{% else %}
						&nbsp;
					{% endif %}
				</div>
				
				<div class="col_66">
					{% if sale_offers %}
						<h2>sale offers today ({{ today.date }})</h2>
						<table class='table'>
							<tr>
								<th>product name</th>
								<th>price</th>
								{% if user.is_authenticated %}
									<th>feasible</th>
								{% endif %}
							</tr>
							{% for sale_offer in sale_offers %}
								<tr>
									<td>{{ sale_offer.product.name }}</td>
									<td align='right'>{{ sale_offer.price }}</td>
									{% if user.is_authenticated %}
										<td>{% if sale_offer.feasible %}V{% endif %}</td>
									{% endif %}
								<tr>
							{% endfor %}
						</table>
					{% else %}
						no records
					{% endif %}
				</div>
			</article>
		</div>
	</div>
</body>

bar/templates/bar/transaction_list.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	{% load staticfiles %}
	<link href={% static "favicon.ico" %} rel="shortcut icon">
	<link rel="stylesheet" href={% static "css/style.css" %}>
	<title></title>  
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>
	<div class="container">

		<header class="header clearfix">
			<div class="logo">
				tango3.bar<br/>
				{{ user }}
			</div>
			
			<nav class="menu_main">
				<ul>
					<li><a href={% url 'bar:food_material_list' %}>food materials</a></li>
					<li><a href={% url 'bar:product_list' %}>products</a></li>
					<li><a href={% url 'bar:sale_offer_list' %}>sale offers</a></li>
					<li class="active"><a href={% url 'bar:transaction_list' %}>transactions</a></li>
				</ul>
			</nav>
		</header>
		
		<div class="info">
			<article class="article clearfix">
				<div class="col_50">
					{% if user.is_authenticated %}
						<form action={% url 'bar:add_transaction' %} method='post'>
							<h2>add transaction</h2>
							{% csrf_token %}
							<input type='submit' class='button' /><br/><br/>
							
							<select name='account'>
								{% for account in accounts %}
									<option value='{{ account.id }}' {% if account.is_default %}selected{% endif %}>
										{{ account.name }}
									</option>
								{% endfor %}
							</select>
							<table class='table'>
								{% for offer in offers %}
									<tr>
										<td><input type="radio" name="sale_offer" id="radio-choice-{{ offer.id }}" tabindex="2" value="{{ offer.id }}" /></td>
										<td><label for="radio-choice-{{ offer.id }}">{{ offer.product.name }}</label></td>
										<td align='right'><label for="radio-choice-{{ offer.id }}"><strong>{{ offer.price }}</strong></label></td>
									</tr>
								{% endfor %}
							</table>
						</form>
						
						<hr/>
						
						<form action={% url 'bar:add_account' %} method='post'>
							<h2>add account</h2>
							{% csrf_token %}
							
							<p class="col_50">
								<label for='name'>name</label><br/>
								<input type='text' name='name' id='name'/>
							</p>
							
							<p class="col_50">
								<label for="is_default"><input type="checkbox" name="is_default" id="is_default" /> is default</label><br/>
								<label for="costed"><input type="checkbox" name="costed" id="costed" /> costed</label>
							</p>
							
							<div class="clearfix"></div><br/>
							
							<p class='col_100'>
								<input type='submit' class='button'/>
							</p>
						</form>
					{% else %}
						&nbsp;
					{% endif %}
				</div>
				
				<div class="col_50">
					<h2>transactions today ({{ today.date }})</h2>
					<table class='table'>
						<tr>
							<th>account</th>
							<th>name</th>
							<th>summ</th>
						</tr>
						{% for transaction in transactions %}
							<tr>
								<td>{{ transaction.account.name }}</td>
								<td>{{ transaction.sale_offer.product.name }}</td>
								<td align='right'>{{ transaction.summ }}</td>
							</tr>
						{% endfor %}
					</table>
					
					<hr/>
					
					<h2>totals today ({{ today.date }})</h2>
					<table class='table'>
						{% for row in totals %}
							<tr>
								<td>{{ row.account__name }}</td>
								<td align='right'>{{ row.summ }}</td>
							</tr>
						{% endfor %}
					</table>
				</div>
			</article>
		</div>
	</div>
</body>